### ISSUE TITLE
Error installing Tower via this puppet module.

### ISSUE THREAD

**Issue by stuartflanagan** [boxen/puppet-tower#4]
Error message is: `Error: /Stage[main]/Tower/Package[Tower]/ensure: change from absent to present failed: Unknown flavor`

Also the URL seems malformed in `manifests/init.pp`

**Comment by jacobbednarz** [comment]
This module has been deprecated in favour of [Boxen's inbuilt support for Homebrew/Caskroom](https://github.com/boxen/puppet-boxen/blob/master/manifests/personal.pp#L14-L17)
